# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'defy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for defy
#  pod 'Bitski', '0.4.1'
  #pod 'Web3', '0.3.0'
  #pod 'Web3/PromiseKit', '0.3.0'
  #pod 'Web3/ContractABI', '0.3.0'
    pod 'PromiseKit'
    pod 'Sourcery'
    pod 'Web3Swift.io'
    pod 'AwaitKit', '~> 5.1.0'
    pod 'Plaid'
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'

end
